### ISSUE TITLE
Failing racing condition if built with -j > 1

### ISSUE THREAD

**Issue by vanyasem** [ubports/gsettings-qt#2] opened 2018-09-19 17:05 UTC
Fails to build if `make -jN` is bigger than one. Probably due to a racing condition.

Full build log: https://paste.ubuntu.com/p/pPJThD3w7M/
```
g++ -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o cpptest cpptest.o   -L/home/vanyasem/Projects/AUR/_Unity8/_Unity8-Arch/gsettings-qt-git/src/gsettings-qt/tests/../src -lgsettings-qt -lQt5Test -lQt5Core -lpthread 
/usr/bin/ld: cannot find -lgsettings-qt
collect2: error: ld returned 1 exit status
```

**Comment by z3ntu** [comment] 2020-04-25 10:22
~~Can't reproduce~~ Saw this once now, but it's very sporadic

**Comment by z3ntu** [comment] 2020-04-25 12:33
Another instance:
```
g++ -Wl,--as-needed -Wl,-O1 -shared -o libGSettingsQmlPlugin.so plugin.o gsettings-qml.o moc_plugin.o moc_gsettings-qml.o  -L../src -lgsettings-qt -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl /usr/lib/libQt5Qml.so /usr/lib/libQt5Network.so /usr/lib/libQt5Core.so -lpthread    
make[1]: Leaving directory '/home/pmos/build/src/gsettings-qt-c8ecb2bf269f4ed0a4477bad262751d77ae6bb72/tests'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lgsettings-qt
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.gsettings-qt:169: libGSettingsQmlPlugin.so] Error 1
```

**Comment by z3ntu** [comment] 2020-07-22 20:33
Fixed.

**Comment by peat-psuwit** [comment] 2022-01-10 17:06
As the commit is merged, closing this.

**Closed as completed by peat-psuwit** 2022-01-10 17:06 UTC
Labels: bug
